// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1bcctsv3WbXulPUpfC98cuyErdPanL7w',
    appId: '1:173377252490:web:bec3d7ee908d8612f45173',
    messagingSenderId: '173377252490',
    projectId: 'dormconnect-project',
    authDomain: 'dormconnect-project.firebaseapp.com',
    storageBucket: 'dormconnect-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA033w-RxTJ4bMnLqpofIV6azO4ty9AEg',
    appId: '1:173377252490:android:0ab5029b6fce11b8f45173',
    messagingSenderId: '173377252490',
    projectId: 'dormconnect-project',
    storageBucket: 'dormconnect-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2K8T2aR2zEpYAqsJdL1h7oed7TBhHzc',
    appId: '1:173377252490:ios:66a9a394e48f74baf45173',
    messagingSenderId: '173377252490',
    projectId: 'dormconnect-project',
    storageBucket: 'dormconnect-project.appspot.com',
    iosBundleId: 'com.vivere.dormconnect',
  );
}
